spring:
  application:
    name: pdfassemblyshowcase

signing:
  # has to be true for production
  checkRevocationForUntrustedChains: false
  # for testing purposes set to public tsp url from digicert
  tspSourceUrl: "http://timestamp.digicert.com"
  # optional: not needed for digicert
  tspPolicyOid:
  # bundle: Signing Certificate + with its private key + intermediate ca + root ca (chain muss vollst√§ndig sein)
  pkcs12FileName: "signing.p12"